import Navbar from '@/componente/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Header from '@/componente/Header'
import Footer from '@/componente/Footer'
import LatestRecipes from '@/componente/LatestRecipes'
import Community from '@/componente/Community'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function UserLayout({children}:any)
 {
  return (
    <html lang="en">
      <body className="">
       
        {children}
        <Navbar/>
        <Header/>
        <LatestRecipes/>
        <Community/>
        <Footer/>
      </body>
    
    </html>
  )
}
